name: Django testing and deploy

on:
  push:
    branches: [master]
    
jobs:
  tests:
    runs-on: ubuntu-20.04
    env:
      POSTGRES_USER: ${{ secrets.DB_USER }}
      POSTGRES_PASS: ${{ secrets.DB_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.DB_HOST }}
      POSTGRES_PORT: ${{ secrets.PORT }}
      POSTGRES_DB: ${{ secrets.DB }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      DEBUG: "1"
      
    services:
      postgres_main:
        image: postgres:12
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}  
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASS }} 
          POSTGRES_DB: ${{ env.POSTGRES_DB }} 
        ports: 
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
           
    steps:
      - name: Проверка репозитория на наличие обновлений
        uses: actions/checkout@v3
        
      - name: Установка python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
          
      - name: Установка библиотек
        run: pip install -r requirements.txt
        
      - name: Линтинг
        run: flack8
      
      - name: Тестирование
        run:  pytest .\tests.py -v
        env:
          DB_USER: ${{ env.POSTGRES_USER }}
          DB_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          DB_HOST: ${{ env.POSTGRESHOST }}
          DB_PORT: ${{ env.POSTGRES_PORT }}
          POSTGRES_DB: ${{ secrets.DB }}
          SECRET_KEY: ${{ env.SECRET_KEY }}
          ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS }}
          DEBUG: ${{ env.DEBUG }}
    